version: '3.8'

services:
 app:
  build: ./php
  container_name: lamp-php
  volumes:
    - ./php:/var/www/html
  ports:
    - "8083:80"
  depends_on:
    - db


  db:
    image: mysql:5.7
    container_name: lamp-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lamp-phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass

volumes:
  db_data:
