services:
  app:
    build: ./php
    container_name: lamp-docker-app
    ports:
      - "8083:80"
    volumes:
      - ./php:/var/www/html
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:5.7
    container_name: lamp-docker-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: blogdb
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lamp-docker-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - mysql_db
